console.log("Adição: 1 + 4 =", 1 + 4)
console.log("Subtração: 5 + (-7) =", 5 + -7)
console.log("Subtração: -6.7 - 8.8 =", -6.7 - 8.8)
console.log("Multiplicação: 9 x 8 =", 9 * 8)
console.log("Divisão: 21 ÷ 7 =", 21 / 7)
console.log("Resto da Divisão: 70 ÷ 20 =", 70 % 20)
console.log("Concatenação de duas strings:", "Lucas " + "Souza")
console.log("Pegando o quinto caractere de \"JavaScript\":", "JavaScript"[4])
console.log("Quantidade de caracteres em \"Desenvolvedor\":", "Desenvolvedor".length, "caracteres")
console.log("Eu nasci em Fortaleza-CE há " + 27 + " anos")